INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_PPM_WIEGAND PPM_Wiegand)

FIND_PATH(
    PPM_WIEGAND_INCLUDE_DIRS
    NAMES PPM_Wiegand/api.h
    HINTS $ENV{PPM_WIEGAND_DIR}/include
        ${PC_PPM_WIEGAND_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    PPM_WIEGAND_LIBRARIES
    NAMES gnuradio-PPM_Wiegand
    HINTS $ENV{PPM_WIEGAND_DIR}/lib
        ${PC_PPM_WIEGAND_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PPM_WIEGAND DEFAULT_MSG PPM_WIEGAND_LIBRARIES PPM_WIEGAND_INCLUDE_DIRS)
MARK_AS_ADVANCED(PPM_WIEGAND_LIBRARIES PPM_WIEGAND_INCLUDE_DIRS)

